### PR TITLE
[Mono] Various fixes

### PR DESCRIPTION
**Pull request by martinjt**
Fixed bundling Microsoft.Web.Infrastructure.dll (Mono has it's own).
Fixed cases for Scripts folder for bundles.

### CODE REVIEW

**Comment by martinjt** [comment]
I looked at the script resource mapping, and it looks like it's not being used anywhere at the moment.  I did look at the possibly of implementing it in Mono, but the change is too far reaching at the moment.

Could you explain the need for the script resource and maybe I could find a way around it?  if it's just so that you could choose to use unobtrusive mode in webforms, I could drop it behind a compiler directive so that for Mono it reverts to the old mode?

**Comment by rxtur** [comment]
Martin, there seems to be couple issues with code you want to merge. It looks like you didn't pull latest and this code will undo some changes, for example jquery updated to version 2.1.4 but your code is going to revert references back to 2.1.1. Also, it adds MonoDevelop metadata to project file.

The resource mapping was added at some point if I'm not mistaken to resolve conflicts between jQuery when more than one version referenced. It shouldn't matter most of the time, but can fix some odd issues. I wouldn't be against removing it though.

**Comment by martinjt** [comment]
I'll fix the {version} parts tonight, missed those as you committed after I forked.

In terms of the monodevelop data, it's just the mono version of the project settings that are already in the file so I didn't see it as an issue.  I was looking at ways to pull it from a .user file, but as you didn't do that for the Visual Studio ones, I figured it would be ok.

For the jQuery one, as it's included as part of a bundle as well, it wouldn't override the version in the bundle anyway.

They'll be a few more of these over the next week or so as there's a few more things that are currently platform specific like using "/" instead of Path.Separator.  On the whole though, it now works out of the box for the most part (for the xml backend that is, not tried the databases).

**Comment by farzindev** [comment]
I'm closing this,
We are working on a new project similar to BlogEngine, please check it out:
https://github.com/blogifierdotnet/Blogifier

**Pull request closed without merging**
